Repository euslisp/EusLisp, pull requests merged in 2018-07, with the labels that each got.

#262 [lisp/geo/geopack.l] normalize norm vector in optional arugment of vector-angle function.
  lisp/geo/geopack.l
Labels: question

#116 add argument to defun
  lisp/c/eus.h
  lisp/c/eus_proto.h
  lisp/c/makes.c
Labels: PR/MergeOK, question

#246 increse max count of pushsequence for 64 bit machine
  lisp/c/sequence.c
Labels: PR/MergeOK
