Repository euslisp/EusLisp, pull requests merged in 2018-08, with the labels that each got.

#254 support supplied-p for &key / &optional
  lisp/c/eval.c
Labels: PR/UpdateAPI, PR/WaitForFeedback, cl-compatible

#315 [cl-compatible] Add caaaar-like functions
  lisp/l/common.l
Labels: ci-compatible/AddMissingFeature

#313 [cl-compatible] Fix assoc :key and add *-if *-if-not functions
  lisp/c/eus_proto.h
  lisp/c/lists.c
  lisp/comp/builtins.l
  lisp/l/common.l
  lisp/l/eusstart.l
  lisp/l/exports.l
Labels: ci-compatible/AddMissingFeature, ci-compatible/FixBugs

#306 Implement macrolet
  doc/jlatex/jcontrols.tex
  doc/jlatex/jgenerals.tex
  doc/jlatex/jintro.tex
  doc/jlatex/jmanual.dvi
  doc/jlatex/jmanual.pdf
  doc/jlatex/jsymbols.tex
  doc/latex/controls.tex
  doc/latex/generals.tex
  doc/latex/intro.tex
  doc/latex/manual.dvi
  doc/latex/manual.pdf
  doc/latex/symbols.tex
  lisp/c/eus_proto.h
  lisp/c/makes.c
  lisp/c/specials.c
  lisp/l/eusstart.l
  lisp/l/exports.l
Labels: ci-compatible/AddMissingFeature, cl-compatible

#308 [cl-compatible] Return variable name in defparameter and defconstant
  lisp/l/common.l
Labels: ci-compatible/ChangeExistingFeature

#307 [cl-compatible] Return T when AND has no arguments
  lisp/c/specials.c
Labels: ci-compatible/ChangeExistingFeature
